{% set name = "proptimus-raphan" %}
{% set version = load_file_regex(config, '../pyproject.toml', 'version = "([^"]+)"', 1) %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: $PYTHON -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - biopython
    - rdkit
    - xtb
    - tqdm

test:
  commands:
    - raphan --help

about:
  home: https://github.com/sb-ncbr/proptimus_raphan
  license: MIT
  license_file: LICENSE
  summary: Rapid constrained alpha-carbon optimisation using overlapping substructures.

extra:
  recipe-maintainers:
    - sb-ncbr
